Cherry-pick r270665. rdar://problem/74105427
    Removing unnecessary locking from JSValue API functions
    https://bugs.webkit.org/show_bug.cgi?id=219723

    Reviewed by Filip Pizlo.

    PerformanceTests:

    Print an error message when benchmarks fail to run and add option to change
    the configuration used to build the benchmarks.

    * APIBench/api-bench:

    Source/JavaScriptCore:

    Remove the unnecessary locking from the JSValueIs* and JSValueMake* API functions
    that only work on primitives. Also remove the unnecessary method dispatching and
    call from the -[JSValue is*] methods.

    This improves the APIBench score by another ~8% since these are such common operations.
    Here are the results: (Baseline includes https://bugs.webkit.org/show_bug.cgi?id=219663)

    CURRENT_API:        Baseline   Change
    ----------------------------------------
    RichardsMostlyC:      74ms      60ms
    RichardsMostlyObjC:  304ms     300ms
    RichardsMostlySwift: 305ms     293ms
    RichardsSomeC:        97ms      77ms
    RichardsSomeObjC:    158ms     159ms
    RichardsSomeSwift:   202ms     198ms

    UPCOMING_API:       Baseline   Change
    ----------------------------------------
    RichardsMostlyC:      23ms      19ms
    RichardsMostlyObjC:  282ms     282ms
    RichardsMostlySwift: 280ms     282ms
    RichardsSomeC:        95ms      76ms
    RichardsSomeObjC:    157ms     156ms
    RichardsSomeSwift:   202ms     197ms
    ----------------------------------------
    Score:             33.6404   36.4006

    * API/APICast.h:
    (toRef):
    * API/JSValue.mm:
    (-[JSValue isUndefined]):
    (-[JSValue isNull]):
    (-[JSValue isBoolean]):
    (-[JSValue isNumber]):
    (-[JSValue isString]):
    (-[JSValue isObject]):
    (-[JSValue isSymbol]):
    * API/JSValueRef.cpp:
    (JSValueGetType):
    (JSValueIsUndefined):
    (JSValueIsNull):
    (JSValueIsBoolean):
    (JSValueIsNumber):
    (JSValueIsString):
    (JSValueIsObject):
    (JSValueIsSymbol):
    (JSValueMakeUndefined):
    (JSValueMakeNull):
    (JSValueMakeBoolean):
    (JSValueMakeNumber):

    Canonical link: https://commits.webkit.org/232328@main
    git-svn-id: https://svn.webkit.org/repository/webkit/trunk@270665 268f45cc-cd09-0410-ab3c-d52691b4dbfc

Canonical link: https://commits.webkit.org/232923.169@safari-611-branch
git-svn-id: https://svn.webkit.org/repository/webkit/branches/safari-611-branch@272538 268f45cc-cd09-0410-ab3c-d52691b4dbfc

diff --git a/PerformanceTests/APIBench/api-bench b/PerformanceTests/APIBench/api-bench
--- a/PerformanceTests/APIBench/api-bench
+++ b/PerformanceTests/APIBench/api-bench
@@ -37,6 +37,7 @@ REFERENCES=("X")
 CURRENT_API=()
 UPCOMING_API=()
 ARCHS=${ARCHS:-$(uname -m)}
+CONFIGURATION=${CONFIGURATION:-Release}
 
 shouldBuild=true
 runReferences=true
@@ -148,7 +149,7 @@ buildBenchmark() {
     fi
 
     log "Building $BENCHMARK_NAME... (FRAMEWORK_SEARCH_PATHS='$BUILD_DIRECTORY')"
-    xcodebuild -project "$project" -target "$BENCHMARK_NAME" -configuration Release build "FRAMEWORK_SEARCH_PATHS='$BUILD_DIRECTORY'" "ARCHS='$ARCHS'"
+    xcodebuild -project "$project" -target "$BENCHMARK_NAME" -configuration "$CONFIGURATION" build "FRAMEWORK_SEARCH_PATHS='$BUILD_DIRECTORY'" "ARCHS='$ARCHS'"
 }
 
 build() {
@@ -161,9 +162,14 @@ runJSBenchmark() {
 }
 
 runNativeBenchmark() {
-    pushd "build/Release" &> /dev/null
+    pushd "build/$CONFIGURATION" &> /dev/null
     "./$BENCHMARK_NAME"
+    local exitCode=$?
+    if [ $exitCode -ne 0 ]; then
+        echo "Benchmark exited with an error: $PWD/$BENCHMARK_NAME exited with $exitCode" 1>&2
+    fi
     popd &> /dev/null
+    return $exitCode
 }
 
 runBenchmarkIteration() {
@@ -179,6 +185,9 @@ runBenchmark() {
 
     local result
     result=$(runBenchmarkIteration)
+    if [ $? -ne 0 ]; then
+        exit 1
+    fi
     RESULTS[$((BENCHMARK_ID * iterations + ITERATION))]=$result
     log "Finished in ${result}ms"
 }
