Minor changes to the build system:     - Sub makefiles now pickup configure-generated compiler flag settings correctly     - Some cosmetic updates to echo output
Canonical link: https://commits.webkit.org/64@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@66 268f45cc-cd09-0410-ab3c-d52691b4dbfc

diff --git a/WebCore/configure.in b/WebCore/configure.in
--- a/WebCore/configure.in
+++ b/WebCore/configure.in
@@ -50,9 +50,15 @@ SUBDIRS='
 for subdir in $SUBDIRS; do
 	if (test -f "./$subdir/MakeSystemChanges.sh"); then
 		CWD=`pwd`
-		echo ">>> Setting up in $subdir";
+		echo "setting up $subdir...";
 		cd $subdir;
 		./MakeSystemChanges.sh;
+                if ( test "$?" = "0" ); then
+                    echo ">>> setup ok"
+                else
+                    echo ">>> setup fail"
+                    exit 1
+                fi
 		cd $CWD;
 	fi
 done
