WebCore: 	Changed WebCore to build as a framework, not a dylib, so resources 	can be added to it.
	* Makefile.am: Actual changes to build WebCore.framework
	* Resources/Info.plist: Added.
	* English.lproj/InfoPlist.strings: Added.
	* WebCore-tests.exp: Added.
	* WebCore.exp: Added.
	* libwebcore.exp: Removed.
	* libwebcoretests.exp: Removed.
	* .cvsignore: Updated.

WebKit:
	* WebKit.pbproj/project.pbxproj: Link against WebCore.framework,
	not libwebcore.dylib.

WebBrowser:
	* WebBrowser.pbproj/project.pbxproj: Link against
	WebCore.framework, not libwebcore.dylib.

Top level:
	Link against WebCore.framework, not libwebcore.dylib.

	* Tests/kde/Makefile.am:
	* Tests/khtmlview/WebViewTest/WebViewTest.pbproj/project.pbxproj:
	* Tests/qt/Makefile.am:


Canonical link: https://commits.webkit.org/1112@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@1217 268f45cc-cd09-0410-ab3c-d52691b4dbfc

diff --git a/WebCore/Makefile.am b/WebCore/Makefile.am
--- a/WebCore/Makefile.am
+++ b/WebCore/Makefile.am
@@ -4,57 +4,21 @@ SUBDIRS = khtml kwq
 
 symrootsdir = $(SYMROOTS)
 
-symroots_LIBRARIES = libwebcore.dylib
+noinst_LIBRARIES = libwebcore.dylib
 
-noinst_LIBRARIES = libwebcoreunstripped.dylib
-
-libwebcoreunstripped_dylib_SOURCES = \
+libwebcore_dylib_SOURCES = \
 	dummy.mm \
 	$(NULL)
 
-libwebcoreunstripped_dylib_LIBADD = \
+libwebcore_dylib_LIBADD = \
 	./khtml/libkhtml.o \
 	./kwq/libkwq.o \
 	$(NULL)
 
-LIBWEBCORE_INSTALL_PATH = @executable_path/../Frameworks
+WEBCORE_INSTALL_PATH = $(SYMROOTS)
 
-DYLIB_NAME = libwebcore.dylib
-EMBED_HOST = $(SYMROOTS)/Alexander.app
-EMBED_DIR = $(EMBED_HOST)/Contents/Frameworks
-
-libwebcorecombined.exp: libwebcore.exp libwebcoretests.exp
+WebCore-combined.exp: WebCore.exp WebCore-tests.exp
 	cat $^ > $@
-
-libwebcorenmedited.dylib: libwebcoreunstripped.dylib libwebcorecombined.exp
-	nmedit -s libwebcorecombined.exp -o $@ - $<
-
-libwebcore.dylib: libwebcorenmedited.dylib
-	if test -z "$(STRIP_FLAGS)"; then \
-	    ln -f $< $@; \
-	else \
-	    strip $(STRIP_FLAGS) -o $@ - $<; \
-	fi
-
-embed:
-	@if test -f "$(DYLIB_NAME)"; then \
-		INSTALL_PATH=`otool -D "$(DYLIB_NAME)"`; \
-		WILL_EMBED=`echo $$INSTALL_PATH | sed -n -e "s/@executable_path//p"`; \
-		if test -n "$$WILL_EMBED"; then \
-			if [ -d "$(EMBED_HOST)" ]; then \
-				if [ ! -d "$(EMBED_DIR)" ]; then \
-					mkdir -p "$(EMBED_DIR)"; \
-				fi; \
-				echo "embedding $(DYLIB_NAME) into $(EMBED_HOST)..."; \
-				cp -f $(DYLIB_NAME) $(EMBED_DIR); \
-			else \
-				echo "$(EMBED_HOST) not found. Not embedding framework"; \
-			fi; \
-		fi; \
-        else \
-		echo "can't find: $(DYLIB_NAME)"; \
-		exit 1; \
-        fi
 
 LDFLAGS = \
 	-framework Cocoa \
@@ -68,14 +32,88 @@ LDFLAGS = \
         -undefined error \
         -all_load \
 	-seg1addr 0x2200000 \
-        -install_name $(LIBWEBCORE_INSTALL_PATH)/libwebcore.dylib \
 	$(NULL)
 
-libwebcoreunstripped_dylib_AR = $(OBJCXXLD) $(AM_OBJCXXFLAGS) $(OBJCXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o
+libwebcore_dylib_AR = touch libwebcore.dylib; :
 
-noinst_DATA = webcore-install-stamp
+noinst_DATA = framework-stamp framework-resource-stamp framework-dylib-stamp framework-header-stamp WebCore-combined.exp
 
-webcore-install-stamp: libwebcore.dylib
-	$(MAKE) install-symrootsLIBRARIES
-	$(MAKE) embed
-	touch ./webcore-install-stamp
+# Framework assembly
+
+FRAMEWORK_NAME = WebCore
+FRAMEWORK_VERSION = A
+FRAMEWORK_RESOURCES = Resources/Info.plist
+FRAMEWORK_LOCALIZED_RESOURCES = English.lproj/InfoPlist.strings
+
+
+FRAMEWORK_DIR = $(SYMROOTS)/$(FRAMEWORK_NAME).framework
+FRAMEWORK_DYLIB = $(FRAMEWORK_DIR)/Versions/$(FRAMEWORK_VERSION)/$(FRAMEWORK_NAME)
+FRAMEWORK_LINKFLAGS = $(libwebcore_dylib_LIBADD) -install_name @executable_path/../Frameworks/$(FRAMEWORK_NAME).framework/Versions/$(FRAMEWORK_VERSION)/$(FRAMEWORK_NAME)
+FRAMEWORK_RESOURCE_DIR = $(FRAMEWORK_DIR)/Versions/$(FRAMEWORK_VERSION)/Resources
+FRAMEWORK_LOCALIZED_RESOURCE_DIR = $(FRAMEWORK_RESOURCE_DIR)/English.lproj
+
+framework-stamp: framework-dylib-stamp framework-resource-stamp framework-header-stamp
+	$(MAKE) embed && \
+	touch ./framework-stamp
+
+framework-resource-stamp: $(FRAMEWORK_RESOURCES) $(FRAMEWORK_LOCALIZED_RESOURCES)
+	rm -rf $(FRAMEWORK_RESOURCE_DIR)
+	mkdir -p $(FRAMEWORK_RESOURCE_DIR)
+	ln -sf Versions/Current/Resources $(FRAMEWORK_DIR)/Resources
+	@list='$(FRAMEWORK_RESOURCES)'; for p in $$list; do \
+		echo " $(INSTALL_DATA) $$p $(FRAMEWORK_RESOURCE_DIR)/$$p"; \
+	    	$(INSTALL_DATA) $$p $(FRAMEWORK_RESOURCE_DIR); \
+	done
+	mkdir -p $(FRAMEWORK_LOCALIZED_RESOURCE_DIR)
+	@list='$(FRAMEWORK_LOCALIZED_RESOURCES)'; for p in $$list; do \
+		echo " $(INSTALL_DATA) $$p $(FRAMEWORK_LOCALIZED_RESOURCE_DIR)/$$p"; \
+		$(INSTALL_DATA) $$p $(FRAMEWORK_LOCALIZED_RESOURCE_DIR); \
+	done
+	touch ./framework-resource-stamp
+
+framework-header-stamp:
+	mkdir -p $(FRAMEWORK_DIR)/Versions/$(FRAMEWORK_VERSION)/Headers
+	mkdir -p $(FRAMEWORK_DIR)/Versions/$(FRAMEWORK_VERSION)/PrivateHeaders
+	ln -sf Versions/Current/Headers $(FRAMEWORK_DIR)/Headers
+	ln -sf Versions/Current/PrivateHeaders $(FRAMEWORK_DIR)/PrivateHeaders
+	touch ./framework-header-stamp
+
+framework-dylib-stamp: $(libwebcore_dylib_OBJECTS) $(libwebcore_dylib_DEPENDENCIES) WebCore-combined.exp
+	mkdir -p $(FRAMEWORK_DIR)/Versions/$(FRAMEWORK_VERSION)
+	rm -f $(FRAMEWORK_DIR)/Versions/Current
+	ln -sf $(FRAMEWORK_VERSION) $(FRAMEWORK_DIR)/Versions/Current
+	$(OBJCXXLD) $(AM_OBJCXXFLAGS) $(OBJCXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) $(FRAMEWORK_LINKFLAGS) $(libwebcore_dylib_OBJECTS) -o $(FRAMEWORK_DYLIB)
+	nmedit -s WebCore-combined.exp - $(FRAMEWORK_DYLIB)
+	ln -sf Versions/Current/$(FRAMEWORK_NAME) $(FRAMEWORK_DIR)/$(FRAMEWORK_NAME)
+	touch ./framework-dylib-stamp
+
+
+CLEANFILES = $(noinst_DATA)
+# can't use CLEANFILES for this because it doesn't work for directories
+clean-am:
+	rm -rf $(FRAMEWORK_DIR)
+
+# Embedding into Alexander
+
+EMBED_HOST = $(SYMROOTS)/Alexander.app
+EMBED_DIR = $(EMBED_HOST)/Contents/Frameworks
+
+embed:
+	@if test -f "$(FRAMEWORK_DYLIB)"; then \
+		INSTALL_PATH=`otool -D "$(FRAMEWORK_DYLIB)"`; \
+		WILL_EMBED=`echo $$INSTALL_PATH | sed -n -e "s/@executable_path//p"`; \
+		if test -n "$$WILL_EMBED"; then \
+			if [ -d "$(EMBED_HOST)" ]; then \
+				if [ ! -d "$(EMBED_DIR)" ]; then \
+					mkdir -p "$(EMBED_DIR)"; \
+				fi; \
+				echo "embedding $(FRAMEWORK_NAME) into $(EMBED_HOST)..."; \
+				cp -rf $(FRAMEWORK_DIR) $(EMBED_DIR); \
+			else \
+				echo "$(EMBED_HOST) not found. Not embedding framework"; \
+			fi; \
+		fi; \
+        else \
+		echo "can't find: $(FRAMEWORK_DYLIB)"; \
+		exit 1; \
+        fi
