top level:
	* configure.in: Update for new organization of WebCore.

	* Tools/HotSpotFinder/HotSpotFinder.pbproj/project.pbxproj: Switch to gcc3 and
	turn on more warnings.
	* Tools/HotSpotFinder/SamplingData.m:
	(-[SamplingDataAccumulator processFunction:depth:]): Fix a signed/unsigned warning.

WebCore:

	* .cvsignore: Ignore new generated files at this level.

	* include/*: Removed. We don't need this hack any more.
	* src/*: Removed. Sources are now in their new locations.
	* src/libwebcore.exp: Removed. This is now in its new location.
	* src/libwebcoretests.exp: Removed. This is now in its new location.

	* Makefile.am: Build khtml and kwq subdirs, don't build src and include.
	Also add the rules that used to be in src about linking the library and
	the rules that used to be in src/kdelibs/kdecore about building the
	kentitices.c file.

	* dummy.mm: Moved here from src by hand.
	* kentities.gperf: Moved here from src/kdelibs/kdecore by hand.

	* khtml/html/Makefile.am: Add WebCore directory to includes so the
	include of "kentities.c" will work.

	* kwq/KWQKHTMLPart.mm:
	* kwq/KWQKJavaEmbed.mm:
	* kwq/KWQKloader.mm:
	Correct includes so we don't need a -I for each of the subdirectories.

	* kwq/khtml/java/javaembed.h: Removed. We use the one in the real
	khtml directory.

	* kwq/kwqdebug.h: Rolled over Chris's changes, which were done after
	the cvs surgery was done.

WebKit:

	* WebKit.pbproj/project.pbxproj: Update header search paths to find
	WebCore in the new location and eliminate WebCore/include.

WebBrowser:

	* WebBrowser.pbproj/project.pbxproj: Update header search paths to find
	WebCore in the new location and eliminate WebCore/include.


Canonical link: https://commits.webkit.org/948@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@1039 268f45cc-cd09-0410-ab3c-d52691b4dbfc

diff --git a/WebCore/Makefile.am b/WebCore/Makefile.am
--- a/WebCore/Makefile.am
+++ b/WebCore/Makefile.am
@@ -1,8 +1,91 @@
 NULL=
 
-SUBDIRS = \
-	src \
-	include \
+SUBDIRS = . khtml kwq
+
+symrootsdir = $(SYMROOTS)
+
+symroots_LIBRARIES = libwebcore.dylib
+
+noinst_LIBRARIES = libwebcoreunstripped.dylib
+
+libwebcoreunstripped_dylib_SOURCES = \
+	dummy.mm \
 	$(NULL)
 
+libwebcoreunstripped_dylib_LIBADD = \
+	./khtml/libkhtml.o \
+	./kwq/libkwq.o \
+	-ljpeg \
+	$(NULL)
 
+LIBWEBCORE_INSTALL_PATH = @executable_path/../Frameworks
+
+DYLIB_NAME = libwebcore.dylib
+EMBED_HOST = $(SYMROOTS)/Alexander.app
+EMBED_DIR = $(EMBED_HOST)/Contents/Frameworks
+
+libwebcorecombined.exp: libwebcore.exp libwebcoretests.exp
+	cat $^ > $@
+
+libwebcorenmedited.dylib: libwebcoreunstripped.dylib libwebcorecombined.exp
+	nmedit -s libwebcorecombined.exp -o $@ - $<
+
+libwebcore.dylib: libwebcorenmedited.dylib
+	if test -z "$(STRIP_FLAGS)"; then \
+	    ln -f $< $@; \
+	else \
+	    strip $(STRIP_FLAGS) -o $@ - $<; \
+	fi
+
+embed:
+	@if test -f "$(DYLIB_NAME)"; then \
+		INSTALL_PATH=`otool -D "$(DYLIB_NAME)"`; \
+		WILL_EMBED=`echo $$INSTALL_PATH | sed -n -e "s/@executable_path//p"`; \
+		if test -n "$$WILL_EMBED"; then \
+			if [ -d "$(EMBED_HOST)" ]; then \
+				if [ ! -d "$(EMBED_DIR)" ]; then \
+					mkdir -p "$(EMBED_DIR)"; \
+				fi; \
+				echo "embedding $(DYLIB_NAME) into $(EMBED_HOST)..."; \
+				cp -f $(DYLIB_NAME) $(EMBED_DIR); \
+			else \
+				echo "$(EMBED_HOST) not found. Not embedding framework"; \
+			fi; \
+		fi; \
+        else \
+		echo "can't find: $(DYLIB_NAME)"; \
+		exit 1; \
+        fi
+
+LDFLAGS = \
+	-framework Cocoa \
+	-framework CoreFoundation \
+	-F$(symrootsdir) \
+	-framework WebFoundation \
+	-framework JavaScriptCore \
+        -dynamiclib \
+	-twolevel_namespace \
+	-prebind \
+        -undefined error \
+        -all_load \
+	-seg1addr 0x2200000 \
+        -install_name $(LIBWEBCORE_INSTALL_PATH)/libwebcore.dylib \
+	$(NULL)
+
+libwebcoreunstripped_dylib_AR = $(OBJCXXLD) $(AM_OBJCXXFLAGS) $(OBJCXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o
+
+noinst_DATA = webcore-install-stamp
+
+webcore-install-stamp: libwebcore.dylib
+	$(MAKE) install-symrootsLIBRARIES
+	$(MAKE) embed
+	touch ./webcore-install-stamp
+
+noinst_HEADERS = kentities.c
+
+BUILT_SOURCES = $(noinst_HEADERS)
+
+kentities.c: kentities.gperf
+	$(GPERF) -a -L "ANSI-C" -C -G -c -o -t -k '*' -NfindEntity -D -s 2 $< > $@
+
+CLEANFILES = $(BUILT_SOURCES)
