2002-03-26  Kenneth Kocienda  <kocienda@apple.com>
        These changes help the transition to the new build system which unifies
        our development build setting with the settings we use to ship
        releases.

        Labyrinth:

        Removed --enable-alexander-test configure option
        Added --with-buildstyle option

        * configure.in:


        WebFoundation:

        * WebFoundation.pbproj/project.pbxproj:


        WebKit:

        * Makefile.am:
        * WebKit.pbproj/kocienda.pbxuser:
        * WebKit.pbproj/project.pbxproj:


        WebBrowser:

        * Makefile.am:
        * WebBrowser.pbproj/project.pbxproj:


Canonical link: https://commits.webkit.org/806@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@864 268f45cc-cd09-0410-ab3c-d52691b4dbfc

diff --git a/WebCore/src/Makefile.am b/WebCore/src/Makefile.am
--- a/WebCore/src/Makefile.am
+++ b/WebCore/src/Makefile.am
@@ -22,11 +22,31 @@ libwebcore_dylib_LIBADD = \
 	$(NULL)
 
 
-if AlexanderTest
-LIBWEBCORE_INSTALL_PATH=@executable_path/../Frameworks
-else
-LIBWEBCORE_INSTALL_PATH=$(symrootsdir)
-endif
+LIBWEBCORE_INSTALL_PATH = @executable_path/../Frameworks
+
+DYLIB_NAME = libwebcore.dylib
+EMBED_HOST = $(SYMROOTS)/Alexander.app
+EMBED_DIR = $(EMBED_HOST)/Contents/Frameworks
+
+embed:
+	@if test -f "$(DYLIB_NAME)"; then \
+		INSTALL_PATH=`otool -D "$(DYLIB_NAME)"`; \
+		WILL_EMBED=`echo $$INSTALL_PATH | sed -n -e "s/@executable_path//p"`; \
+		if test -n "$$WILL_EMBED"; then \
+			if [ -d "$(EMBED_HOST)" ]; then \
+				if [ ! -d "$(EMBED_DIR)" ]; then \
+					mkdir -p "$(EMBED_DIR)"; \
+				fi; \
+				echo "embedding $(DYLIB_NAME) into $(EMBED_HOST)..."; \
+				cp -f $(DYLIB_NAME) $(EMBED_DIR); \
+			else \
+				echo "$(EMBED_HOST) not found. Not embedding framework"; \
+			fi; \
+		fi; \
+        else \
+		echo "can't find: $(DYLIB_NAME)"; \
+		exit 1; \
+        fi
 
 LDFLAGS = \
 	-framework Cocoa \
